[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit = "GWZPQsbLKGnB8rQptKGDFsZ3PtbsYPFxhXm8NyhoftbY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/elijah/solanaDevCourse/solana-movie-frontend/SDCcPraNtvK4XPk5XASqYExWyEPrH9YAnEwm6Hcuz3U.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
